import { useState, useEffect, createContext, useContext, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation dictionaries
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.courses': 'Courses',
    'nav.about': 'About',
    'nav.tasks': 'Tasks',
    'nav.contact': 'Contact',
    'nav.admin': 'Admin',
    'nav.signin': 'Sign in',
    'nav.signup': 'Sign up',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.signout': 'Sign out',
    'nav.notifications': 'Notifications',
    'nav.messages': 'Messages',
    'nav.language.select': 'Select Language',
    
    // Home Page
    'home.hero.title': 'Master English with',
    'home.hero.subtitle': 'Advanced Learning Technology',
    'home.hero.description': 'Experience Vietnam\'s most advanced English learning platform. Combining proven international methodologies with cutting-edge AI technology for guaranteed results.',
    'home.hero.startLearning': 'Start Learning',
    'home.hero.takeLevelTest': 'Take Level Test',
    'home.hero.myDashboard': 'My Dashboard',
    'home.stats.expertTeachers': 'Expert Teachers',
    'home.stats.activeStudents': 'Active Students',
    'home.stats.successRate': 'Success Rate',
    'home.stats.courseCategories': 'Course Categories',
    'home.popular.title': 'Most Popular Courses',
    'home.popular.description': 'Join thousands of successful students in our most popular English courses',
    'home.popular.viewAll': 'View All Popular Courses',
    'home.featured.title': 'Featured Courses',
    'home.featured.description': 'Explore our most comprehensive and highly-rated English courses',
    'home.featured.exploreAll': 'Explore All Courses',
    'home.cta.title': 'Start Your English Journey Today',
    'home.cta.description': 'Experience world-class education in Northern Vietnam. Take our AI-powered placement test and start your personalized learning journey with guaranteed results.',
    'home.cta.startTrial': 'Start Free Trial',
    'home.cta.bookConsultation': 'Book Consultation',
    'home.cta.freePlacementTest': 'Free Placement Test',
    'home.cta.guarantee': '30-Day Guarantee',
    'home.cta.support': '24/7 Support',
    
    // Courses Page
    'courses.title': 'Explore Our Courses',
    'courses.description': 'Discover comprehensive English courses designed for all levels and learning objectives. Find your perfect learning path with our expert-designed curriculum.',
    'courses.stats.available': 'Available Courses',
    'courses.stats.categories': 'Categories',
    'courses.stats.avgRating': 'Avg Rating',
    'courses.stats.successRate': 'Success Rate',
    'courses.search.title': 'Search Courses',
    'courses.search.placeholder': 'Search courses...',
    'courses.filter.level': 'Level',
    'courses.filter.category': 'Category',
    'courses.filter.duration': 'Duration',
    'courses.filter.priceRange': 'Price Range',
    'courses.price.vnd': 'VND',
    'courses.price.thousand': 'k',
    'courses.filter.rating': 'Minimum Rating',
    'courses.filter.reset': 'Reset Filters',
    'courses.sort.by': 'Sort by:',
    'courses.sort.popular': 'Most Popular',
    'courses.sort.rating': 'Highest Rated',
    'courses.sort.newest': 'Newest',
    'courses.sort.price': 'Price: Low to High',
    'courses.sort.alphabetical': 'A to Z',
    'courses.sort.order.highToLow': 'High to Low',
    'courses.sort.order.lowToHigh': 'Low to High',
    'courses.found': 'Courses Found',
    'courses.noResults.title': 'No courses found',
    'courses.noResults.description': 'We couldn\'t find any courses matching your criteria. Try adjusting your filters or search terms.',
    'courses.loadMore': 'Load More Courses',
    
    // Course Card
    'course.level.beginner': 'Beginner',
    'course.level.intermediate': 'Intermediate',
    'course.level.advanced': 'Advanced',
    'course.certificate': 'Certificate',
    'course.enrolled': 'Enrolled',
    'course.continueLearning': 'Continue Learning',
    'course.enrollNow': 'Enroll Now',
    'course.completionRate': 'completion rate',
    'course.lessons': 'lessons',
    'course.free': 'FREE',
    
    // About Page
    'about.title': 'About LERA Academy',
    'about.hero.description': 'Where Excellence is the Standard - Following Apollo English\'s proven methodologies to deliver world-class education with innovative blended learning technology.',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'At LERA Academy, we follow revolutionary educational approaches, combining international teaching standards with innovative blended learning technology. Our certified instructors deliver personalized education through live classes, interactive digital content, and AI-powered progress tracking.',
    'about.stats.yearsInHaiPhong': 'Years in Hai Phong',
    'about.stats.studentsTaught': 'Students Taught',
    'about.stats.successRate': 'Success Rate',
    'about.stats.expertTeachers': 'Expert Teachers',
    'about.cta.title': 'Start Your English Journey Today',
    'about.cta.description': 'Join Hai Phong\'s leading English language center and learn from our team of international experts.',
    'about.cta.bookConsultation': 'Book a Free Consultation',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.description': 'Have questions? We\'re here to help you achieve your English learning goals.',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.workingHours': 'Working Hours',
    'contact.workingHours.weekdays': 'Monday - Friday: 8:00 AM - 8:00 PM',
    'contact.workingHours.saturday': 'Saturday: 8:00 AM - 5:00 PM',
    'contact.form.title': 'Send us a Message',
    'contact.form.fullName': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.visit.title': 'Visit Our Center',
    'contact.visit.mainCenter': 'Main Center',
    'contact.visit.branchLocation': 'Branch Location',
    
    // Common
    'common.welcome': 'Welcome',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.yes': 'Yes',
    'common.no': 'No',
    
    // Auth Page
    'auth.signin.title': 'Sign in to your account',
    'auth.signin.subtitle': 'Welcome back! Please enter your details',
    'auth.signup.title': 'Create your account',
    'auth.signup.subtitle': 'Join thousands of students learning with LERA Academy',
    'auth.form.name': 'Full Name',
    'auth.form.email': 'Email address',
    'auth.form.password': 'Password',
    'auth.form.confirmPassword': 'Confirm Password',
    'auth.form.rememberMe': 'Remember me',
    'auth.form.forgotPassword': 'Forgot your password?',
    'auth.button.signin': 'Sign In',
    'auth.button.signup': 'Create Account',
    'auth.button.signinWithGoogle': 'Continue with Google',
    'auth.button.signinWithGithub': 'Continue with GitHub',
    'auth.switch.hasAccount': 'Already have an account?',
    'auth.switch.noAccount': 'Don\'t have an account?',
    'auth.demo.title': 'Demo Account:',
    'auth.demo.email': 'Email: demo@lera-academy.com',
    'auth.demo.password': 'Password: demo123456',
    'auth.demo.use': 'Use Demo Account',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Continue your learning journey',
    'dashboard.stats.enrolledCourses': 'Enrolled Courses',
    'dashboard.stats.hoursSpent': 'Hours Spent',
    'dashboard.stats.thisWeek': 'This Week',
    'dashboard.stats.certificates': 'Certificates',
    'dashboard.contineLearning': 'Continue Learning',
    'dashboard.tabs.courses': 'My Courses',
    'dashboard.tabs.analytics': 'Analytics',
    'dashboard.tabs.achievements': 'Achievements',
    'dashboard.tabs.calendar': 'Calendar',
    'dashboard.tabs.wishlist': 'Wishlist',
    
    // Footer
    'footer.description': 'Where Excellence is the Standard. Using proven international methodologies to deliver world-class education in Northern Vietnam.',
    'footer.courses.title': 'Courses',
    'footer.courses.speaking': 'Speaking',
    'footer.courses.writing': 'Writing',
    'footer.courses.grammar': 'Grammar',
    'footer.courses.ielts': 'IELTS Preparation',
    'footer.courses.business': 'Business English',
    'footer.about.title': 'About LERA',
    'footer.about.aboutUs': 'About Us',
    'footer.about.teachers': 'Our Teachers',
    'footer.about.methodology': 'Teaching Method',
    'footer.about.testimonials': 'Success Stories',
    'footer.about.admin': 'Admin Portal',
    'footer.legal.title': 'Legal',
    'footer.legal.terms': 'Terms & Conditions',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.cookies': 'Cookie Policy',
    'footer.legal.refund': 'Refund Policy',
    'footer.copyright': 'LERA Academy. All rights reserved.',
    
    // Course Details
    'courseDetail.instructor': 'Instructor',
    'courseDetail.students': 'students',
    'courseDetail.rating': 'rating',
    'courseDetail.enrollNow': 'Enroll Now',
    'courseDetail.continueLearning': 'Continue Learning',
    'courseDetail.guarantee': '30-Day Money-Back Guarantee',
    'courseDetail.includes.lifetime': 'Full lifetime access',
    'courseDetail.includes.mobile': 'Access on mobile and desktop',
    'courseDetail.includes.certificate': 'Certificate of completion',
    'courseDetail.includes.resources': 'Downloadable resources',
    'courseDetail.content.title': 'Course Content',
    'courseDetail.content.sections': 'sections',
    'courseDetail.content.lectures': 'lectures',
    'courseDetail.content.totalLength': 'total length',
    'courseDetail.whatYouLearn': 'What You\'ll Learn',
    'courseDetail.aboutInstructor': 'About the Instructor',
    'courseDetail.similar': 'Similar Courses',
    'courseDetail.viewAll': 'View all courses',
    
    // Tasks
    'tasks.title': 'My Tasks',
    'tasks.filter.all': 'All Tasks',
    'tasks.filter.pending': 'Pending',
    'tasks.filter.completed': 'Completed',
    'tasks.status.pending': 'Pending',
    'tasks.status.inProgress': 'In Progress',
    'tasks.status.submitted': 'Submitted',
    'tasks.status.completed': 'Completed',
    'tasks.status.overdue': 'Overdue',
    'tasks.priority.low': 'Low',
    'tasks.priority.medium': 'Medium',
    'tasks.priority.high': 'High',
    'tasks.submit': 'Submit Task',
    'tasks.updateSubmission': 'Update Submission',
    'tasks.download': 'Download',
    'tasks.feedback': 'Feedback',
    'tasks.score': 'Score',
    'tasks.due': 'Due',
    'tasks.priority': 'priority',
  },
  vi: {
    // Navigation
    'nav.home': 'Trang Chủ',
    'nav.courses': 'Khóa Học',
    'nav.about': 'Giới Thiệu',
    'nav.tasks': 'Bài Tập',
    'nav.contact': 'Liên Hệ',
    'nav.admin': 'Quản Trị',
    'nav.signin': 'Đăng Nhập',
    'nav.signup': 'Đăng Ký',
    'nav.dashboard': 'Bảng Điều Khiển',
    'nav.profile': 'Hồ Sơ',
    'nav.signout': 'Đăng Xuất',
    'nav.notifications': 'Thông Báo',
    'nav.messages': 'Tin Nhắn',
    'nav.language.select': 'Chọn Ngôn Ngữ',
    
    // Home Page
    'home.hero.title': 'Thành Thạo Tiếng Anh với',
    'home.hero.subtitle': 'Công Nghệ Học Tập Tiên Tiến',
    'home.hero.description': 'Trải nghiệm nền tảng học tiếng Anh tiên tiến nhất Việt Nam. Kết hợp phương pháp giảng dạy quốc tế đã được chứng minh với công nghệ AI tiên tiến để đảm bảo kết quả.',
    'home.hero.startLearning': 'Bắt Đầu Học',
    'home.hero.takeLevelTest': 'Kiểm Tra Trình Độ',
    'home.hero.myDashboard': 'Bảng Điều Khiển',
    'home.stats.expertTeachers': 'Giáo Viên Chuyên Gia',
    'home.stats.activeStudents': 'Học Viên Đang Học',
    'home.stats.successRate': 'Tỷ Lệ Thành Công',
    'home.stats.courseCategories': 'Danh Mục Khóa Học',
    'home.popular.title': 'Khóa Học Phổ Biến Nhất',
    'home.popular.description': 'Tham gia cùng hàng nghìn học viên thành công trong các khóa học tiếng Anh phổ biến nhất',
    'home.popular.viewAll': 'Xem Tất Cả Khóa Học Phổ Biến',
    'home.featured.title': 'Khóa Học Nổi Bật',
    'home.featured.description': 'Khám phá các khóa học tiếng Anh toàn diện và được đánh giá cao nhất',
    'home.featured.exploreAll': 'Khám Phá Tất Cả Khóa Học',
    'home.cta.title': 'Bắt Đầu Hành Trình Tiếng Anh Ngay Hôm Nay',
    'home.cta.description': 'Trải nghiệm giáo dục đẳng cấp thế giới tại Miền Bắc Việt Nam. Làm bài kiểm tra trình độ được hỗ trợ AI và bắt đầu hành trình học tập được cá nhân hóa với kết quả được đảm bảo.',
    'home.cta.startTrial': 'Bắt Đầu Dùng Thử Miễn Phí',
    'home.cta.bookConsultation': 'Đặt Lịch Tư Vấn',
    'home.cta.freePlacementTest': 'Kiểm Tra Trình Độ Miễn Phí',
    'home.cta.guarantee': 'Bảo Hành 30 Ngày',
    'home.cta.support': 'Hỗ Trợ 24/7',
    
    // Courses Page
    'courses.title': 'Khám Phá Các Khóa Học',
    'courses.description': 'Khám phá các khóa học tiếng Anh toàn diện được thiết kế cho tất cả các cấp độ và mục tiêu học tập. Tìm con đường học tập hoàn hảo với chương trình giảng dạy được thiết kế bởi chuyên gia.',
    'courses.stats.available': 'Khóa Học Có Sẵn',
    'courses.stats.categories': 'Danh Mục',
    'courses.stats.avgRating': 'Đánh Giá TB',
    'courses.stats.successRate': 'Tỷ Lệ Thành Công',
    'courses.search.title': 'Tìm Kiếm Khóa Học',
    'courses.search.placeholder': 'Tìm kiếm khóa học...',
    'courses.filter.level': 'Cấp Độ',
    'courses.filter.category': 'Danh Mục',
    'courses.filter.duration': 'Thời Lượng',
    'courses.filter.priceRange': 'Khoảng Giá',
    'courses.price.vnd': 'VND', 
    'courses.price.thousand': 'k',
    'courses.filter.rating': 'Đánh Giá Tối Thiểu',
    'courses.filter.reset': 'Đặt Lại Bộ Lọc',
    'courses.sort.by': 'Sắp xếp theo:',
    'courses.sort.popular': 'Phổ Biến Nhất',
    'courses.sort.rating': 'Đánh Giá Cao Nhất',
    'courses.sort.newest': 'Mới Nhất',
    'courses.sort.price': 'Giá: Thấp đến Cao',
    'courses.sort.alphabetical': 'A đến Z',
    'courses.sort.order.highToLow': 'Cao đến Thấp',
    'courses.sort.order.lowToHigh': 'Thấp đến Cao',
    'courses.found': 'Khóa Học Được Tìm Thấy',
    'courses.noResults.title': 'Không tìm thấy khóa học',
    'courses.noResults.description': 'Chúng tôi không thể tìm thấy khóa học nào phù hợp với tiêu chí của bạn. Hãy thử điều chỉnh bộ lọc hoặc từ khóa tìm kiếm.',
    'courses.loadMore': 'Tải Thêm Khóa Học',
    
    // Course Card
    'course.level.beginner': 'Cơ Bản',
    'course.level.intermediate': 'Trung Cấp',
    'course.level.advanced': 'Nâng Cao',
    'course.certificate': 'Chứng Chỉ',
    'course.enrolled': 'Đã Đăng Ký',
    'course.continueLearning': 'Tiếp Tục Học',
    'course.enrollNow': 'Đăng Ký Ngay',
    'course.completionRate': 'tỷ lệ hoàn thành',
    'course.lessons': 'bài học',
    'course.free': 'MIỄN PHÍ',
    
    // About Page
    'about.title': 'Giới Thiệu LERA Academy',
    'about.hero.description': 'Nơi Sự Xuất Sắc Là Tiêu Chuẩn - Theo đuổi phương pháp đã được chứng minh của Apollo English để mang đến giáo dục đẳng cấp thế giới với công nghệ học tập kết hợp sáng tạo.',
    'about.mission.title': 'Sứ Mệnh Của Chúng Tôi',
    'about.mission.description': 'Tại LERA Academy, chúng tôi theo đuổi các phương pháp giáo dục cách mạng, kết hợp tiêu chuẩn giảng dạy quốc tế với công nghệ học tập kết hợp sáng tạo. Các giảng viên được chứng nhận của chúng tôi cung cấp giáo dục cá nhân hóa thông qua các lớp học trực tiếp, nội dung số tương tác và theo dõi tiến độ được hỗ trợ AI.',
    'about.stats.yearsInHaiPhong': 'Năm tại Hải Phòng',
    'about.stats.studentsTaught': 'Học Viên Đã Dạy',
    'about.stats.successRate': 'Tỷ Lệ Thành Công',
    'about.stats.expertTeachers': 'Giáo Viên Chuyên Gia',
    'about.cta.title': 'Bắt Đầu Hành Trình Tiếng Anh Ngay Hôm Nay',
    'about.cta.description': 'Tham gia trung tâm tiếng Anh hàng đầu Hải Phòng và học từ đội ngũ chuyên gia quốc tế của chúng tôi.',
    'about.cta.bookConsultation': 'Đặt Lịch Tư Vấn Miễn Phí',
    
    // Contact Page
    'contact.title': 'Liên Hệ Với Chúng Tôi',
    'contact.description': 'Có câu hỏi? Chúng tôi sẵn sàng giúp bạn đạt được mục tiêu học tiếng Anh.',
    'contact.phone': 'Điện Thoại',
    'contact.email': 'Email',
    'contact.workingHours': 'Giờ Làm Việc',
    'contact.workingHours.weekdays': 'Thứ 2 - Thứ 6: 8:00 SA - 8:00 CH',
    'contact.workingHours.saturday': 'Thứ 7: 8:00 SA - 5:00 CH',
    'contact.form.title': 'Gửi Tin Nhắn Cho Chúng Tôi',
    'contact.form.fullName': 'Họ và Tên',
    'contact.form.email': 'Địa Chỉ Email',
    'contact.form.phone': 'Số Điện Thoại',
    'contact.form.subject': 'Chủ Đề',
    'contact.form.message': 'Tin Nhắn',
    'contact.form.send': 'Gửi Tin Nhắn',
    'contact.visit.title': 'Ghé Thăm Trung Tâm',
    'contact.visit.mainCenter': 'Trung Tâm Chính',
    'contact.visit.branchLocation': 'Chi Nhánh',
    
    // Common
    'common.welcome': 'Chào mừng',
    'common.loading': 'Đang tải...',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.delete': 'Xóa',
    'common.edit': 'Chỉnh sửa',
    'common.view': 'Xem',
    'common.close': 'Đóng',
    'common.next': 'Tiếp theo',
    'common.previous': 'Trước đó',
    'common.submit': 'Gửi',
    'common.search': 'Tìm kiếm',
    'common.filter': 'Lọc',
    'common.all': 'Tất cả',
    'common.yes': 'Có',
    'common.no': 'Không',
    
    // Auth Page
    'auth.signin.title': 'Đăng nhập vào tài khoản',
    'auth.signin.subtitle': 'Chào mừng trở lại! Vui lòng nhập thông tin',
    'auth.signup.title': 'Tạo tài khoản mới',
    'auth.signup.subtitle': 'Tham gia cùng hàng nghìn học viên tại LERA Academy',
    'auth.form.name': 'Họ và Tên',
    'auth.form.email': 'Địa chỉ email',
    'auth.form.password': 'Mật khẩu',
    'auth.form.confirmPassword': 'Xác nhận mật khẩu',
    'auth.form.rememberMe': 'Ghi nhớ đăng nhập',
    'auth.form.forgotPassword': 'Quên mật khẩu?',
    'auth.button.signin': 'Đăng Nhập',
    'auth.button.signup': 'Tạo Tài Khoản',
    'auth.button.signinWithGoogle': 'Tiếp tục với Google',
    'auth.button.signinWithGithub': 'Tiếp tục với GitHub',
    'auth.switch.hasAccount': 'Đã có tài khoản?',
    'auth.switch.noAccount': 'Chưa có tài khoản?',
    'auth.demo.title': 'Tài khoản demo:',
    'auth.demo.email': 'Email: demo@lera-academy.com',
    'auth.demo.password': 'Mật khẩu: demo123456',
    'auth.demo.use': 'Sử dụng tài khoản demo',
    
    // Dashboard
    'dashboard.welcome': 'Chào mừng trở lại',
    'dashboard.subtitle': 'Tiếp tục hành trình học tập',
    'dashboard.stats.enrolledCourses': 'Khóa Học Đã Đăng Ký',
    'dashboard.stats.hoursSpent': 'Giờ Đã Học',
    'dashboard.stats.thisWeek': 'Tuần Này',
    'dashboard.stats.certificates': 'Chứng Chỉ',
    'dashboard.contineLearning': 'Tiếp Tục Học',
    'dashboard.tabs.courses': 'Khóa Học Của Tôi',
    'dashboard.tabs.analytics': 'Phân Tích',
    'dashboard.tabs.achievements': 'Thành Tích',
    'dashboard.tabs.calendar': 'Lịch Học',
    'dashboard.tabs.wishlist': 'Danh Sách Yêu Thích',
    
    // Footer
    'footer.description': 'Nơi Sự Xuất Sắc Là Tiêu Chuẩn. Sử dụng phương pháp giảng dạy quốc tế đã được chứng minh để mang đến giáo dục đẳng cấp thế giới tại Miền Bắc Việt Nam.',
    'footer.courses.title': 'Khóa Học',
    'footer.courses.speaking': 'Nói',
    'footer.courses.writing': 'Viết',
    'footer.courses.grammar': 'Ngữ Pháp',
    'footer.courses.ielts': 'Luyện Thi IELTS',
    'footer.courses.business': 'Tiếng Anh Thương Mại',
    'footer.about.title': 'Về LERA',
    'footer.about.aboutUs': 'Giới Thiệu',
    'footer.about.teachers': 'Giáo Viên',
    'footer.about.methodology': 'Phương Pháp Giảng Dạy',
    'footer.about.testimonials': 'Câu Chuyện Thành Công',
    'footer.about.admin': 'Cổng Quản Trị',
    'footer.legal.title': 'Pháp Lý',
    'footer.legal.terms': 'Điều Khoản & Điều Kiện',
    'footer.legal.privacy': 'Chính Sách Bảo Mật',
    'footer.legal.cookies': 'Chính Sách Cookie',
    'footer.legal.refund': 'Chính Sách Hoàn Tiền',
    'footer.copyright': 'LERA Academy. Tất cả quyền được bảo lưu.',
    
    // Course Details
    'courseDetail.instructor': 'Giáo Viên',
    'courseDetail.students': 'học viên',
    'courseDetail.rating': 'đánh giá',
    'courseDetail.enrollNow': 'Đăng Ký Ngay',
    'courseDetail.continueLearning': 'Tiếp Tục Học',
    'courseDetail.guarantee': 'Bảo Hành Hoàn Tiền 30 Ngày',
    'courseDetail.includes.lifetime': 'Truy cập trọn đời',
    'courseDetail.includes.mobile': 'Truy cập trên điện thoại và máy tính',
    'courseDetail.includes.certificate': 'Chứng chỉ hoàn thành',
    'courseDetail.includes.resources': 'Tài liệu có thể tải xuống',
    'courseDetail.content.title': 'Nội Dung Khóa Học',
    'courseDetail.content.sections': 'phần',
    'courseDetail.content.lectures': 'bài giảng',
    'courseDetail.content.totalLength': 'tổng thời lượng',
    'courseDetail.whatYouLearn': 'Bạn Sẽ Học Được Gì',
    'courseDetail.aboutInstructor': 'Về Giáo Viên',
    'courseDetail.similar': 'Khóa Học Tương Tự',
    'courseDetail.viewAll': 'Xem tất cả khóa học',
    
    // Tasks
    'tasks.title': 'Bài Tập Của Tôi',
    'tasks.filter.all': 'Tất Cả Bài Tập',
    'tasks.filter.pending': 'Đang Chờ',
    'tasks.filter.completed': 'Đã Hoàn Thành',
    'tasks.status.pending': 'Đang Chờ',
    'tasks.status.inProgress': 'Đang Thực Hiện',
    'tasks.status.submitted': 'Đã Nộp',
    'tasks.status.completed': 'Đã Hoàn Thành',
    'tasks.status.overdue': 'Quá Hạn',
    'tasks.priority.low': 'Thấp',
    'tasks.priority.medium': 'Trung Bình',
    'tasks.priority.high': 'Cao',
    'tasks.submit': 'Nộp Bài Tập',
    'tasks.updateSubmission': 'Cập Nhật Bài Nộp',
    'tasks.download': 'Tải Xuống',
    'tasks.feedback': 'Phản Hồi',
    'tasks.score': 'Điểm',
    'tasks.due': 'Hạn nộp',
    'tasks.priority': 'mức độ ưu tiên',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState(() => {
    // Load from localStorage or default to English
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    // Update document language attribute
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    const translation = translations[language as keyof typeof translations];
    return translation?.[key as keyof typeof translation] || key;
  };

  useEffect(() => {
    // Set initial document language
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};